### PR TITLE
Removed pinned versions from requirements.txt (fixes #310)

### LINKED ISSUE #310: Lax requirered versions
This is an installable app. We should not pin versions in `requirements.txt` unless there is really a specific reason to do this. Some people may be in a situation in that they cannot install `silver` because they cannot move to the specific of a required package.

### PR DESCRIPTION
**Pull request by calind**
The only required package version is `django-jsonfield==0.9.15`

### CODE REVIEW

**Comment by vtemian** [comment]
I really think that this is a bad idea, because when a maintainer from those packages will break the compatibility (eg: `djangorestframework`) will be frustrating to develop  or try something on silver.

**Comment by krodyrobi** [comment]
I don't agree with removing the versions as some might break backwards comparability anytime. Better explicit than implicit imho.

**Comment by rciorba** [comment]
As the others said, I think this is a bad ideea. I actually recall discussing this less than a month ago and deciding we want to pin EVERYTHING, because if we don't deployments won't be repeatable.

**Comment by calind** [comment]
This is an installable package, it is not a deployment unit and I think this is the first thing to consider.

What actually happend is that this has django pinned to 1.8.9 and the main app had it pinned to 1.8.11 (which is the latest security release). After pip resolving the dependencies, it settled for django 1.8.9 leaving the main app in dubious security state.

As a general idea is think it's bad practice to pin versions here. The proper place to do it is in the main app.

**Comment by rciorba** [comment]
@calind OK then, LGTM

**Pull request merged**
