### PR TITLE
Upgrades + fixes #291

### LINKED ISSUE #291: Fix date comparison in docs generator

### PR DESCRIPTION
**Pull request by krodyrobi**
Version 0.1.4:
  
   *  Update dependencies, removed deprecation for upcoming 1.9.2 update (#293)
   *  Unicode casts
   *  Fixed datetime calculation at the end of the year for new subscribers (#291)
   *  Now uses django-annoying for get_object_or_None (#297)

-  [x] stage
-  [ ] pypi
-  [ ] git tag
-  [ ] live

### CODE REVIEW

**Comment by zalmanu** [comment]
LGTM

**Comment by vtemian** [comment]
@krodyrobi what is with this one?

**Comment by krodyrobi** [comment]
@vtemian  was it played upon on the stage? if so I'll release it.

**Comment by vtemian** [comment]
I don't think. Maybe @bogdanpetrea knows more.

I guess that only individual pull requests were run on stage, nit this
particularly.

**Pull request merged**
